server:
  port: 8890

spring:
  application:
    name: netty_client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8880/eureka/

  management:
    endpoints:
      web:
        exposure:
          include: "*"
        cors:
          allowed-origins: "*"
          allowed-methods: "*"