eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          password:
          username:
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
