eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8889/eureka/
server:
  port: 8881
spring:
  application:
    name: config-client
  rabbitmq:
    port: 5672
    host: localhost
    password: guest
    username: guest
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    config:
      profile: dev
      label: master
    discovery:
      enabled: true
      serviceId: config-server